;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	end-of-buffer
	keyboard-escape-quit
	org-self-insert-command
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	autopair-insert-or-skip-quote
	org-force-self-insert
	))
