;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-star
	end-of-buffer
	keyboard-escape-quit
	kill-region
	org-delete-char
	org-promote-subtree
	org-self-insert-command
	tern-ac-dot-complete
	win-switch-dispatch
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	autopair-insert-opening
	autopair-insert-or-skip-quote
	autopair-skip-close-maybe
	ess-smart-comma
	org-beginning-of-line
	org-end-of-line
	org-force-self-insert
	switch-to-buffer
	))
